ci

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -20,17 +20,13 @@ jobs:
       - name: Fix git safe directory
         run: git config --global --add safe.directory $GITHUB_WORKSPACE
 
-      - name: Install lcov
+      - name: Install dependencies
         run: |
-          apt-get update && apt-get install -y lcov git
+          apt-get update && apt-get install -y lcov git llvm
 
-      
       - name: Clone Proto Repository
         run: |
-          # Создаем папку, если её нет
           mkdir -p third_party
-          # Клонируем репозиторий с прото-файлами в нужную папку
-          # Если репозиторий приватный, см. примечание ниже*
           git clone https://github.com/viktoralyoshin/playhub-proto.git third_party/playhub-proto
 
       - name: Configure CMake (Coverage Enabled)
@@ -47,20 +43,19 @@ jobs:
 
       - name: Run Tests
         working-directory: build
-        
         run: ctest --output-on-failure || true
 
       - name: Generate Coverage Report
         run: |
-          # 1. Создаем обертку для llvm-cov (для совместимости с lcov)
+          which llvm-cov || echo "llvm-cov still not found!"
+          llvm-cov --version || true
+
           echo '#!/bin/bash' > llvm-gcov.sh
           echo 'exec llvm-cov gcov "$@"' >> llvm-gcov.sh
           chmod +x llvm-gcov.sh
-
-          # 2. Собираем данные
+      
           lcov --gcov-tool $(pwd)/llvm-gcov.sh --capture --directory build --output-file coverage.info
 
-          # 3. Фильтруем системные файлы, тесты и ваши папки managers/repository (как договаривались)
           lcov --remove coverage.info \
             '/usr/*' \
             '*/_deps/*' \
